[azure]
week6-azure-vm ansible_host=20.0.0.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519 cloud_provider=azure container_image=ghcr.io/simply-justin/wh-caa-w6/hello-world-hybrid:latest container_name=hello-world-hybrid

[esxi]
week6-esxi-vm ansible_host=192.168.1.61 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519 cloud_provider=esxi container_image=ghcr.io/simply-justin/wh-caa-w6/hello-world-hybrid:latest container_name=hello-world-hybrid azure_ssh_host=20.0.0.10

[hybrid:children]
azure
esxi

[hybrid:vars]
testuser_name=testuser
